#!/bin/bash
IMAGE="cheald/dxvk-docker:latest"
DXVK_REPO="https://github.com/doitsujin/dxvk.git"
GITREF="master"

if [[ ! -d dxvk ]] ; then
  git clone $DXVK_REPO
fi

read -p "What branch/tag/gitref do you want to build? [master]: " gitref
gitref=${gitref:-$GITREF}
cd dxvk
git fetch -a
git checkout $gitref
cd ..

forceBuild="y"
if [[ -d out/dxvk-master ]] ; then
  read -p "dxvk-master appears to be built already. Do you want to rebuild it? [y/N]" forceBuild
  forceBuild=${forceBuild:-n}
fi

case $forceBuild in
  [yY])
    docker pull $IMAGE
    if [ $? -ne 0 ] ; then
      echo "Error pulling $IMAGE - building. This may take a bit..."
      docker build . -t $IMAGE
      if [ $? -ne 0 ] ; then
        echo "Error building docker image. Exiting..."
        exit 1
      fi
    fi
    docker run -e UID=$UID -e GID=$(id -g $USER) -it -v $(pwd)/dxvk:/root/build $IMAGE
    rm -rf out
    mv dxvk/out .
    ;;
  *)
    echo "Skipping build..."
    ;;
esac

read -p "Install dxvk-master to Lutris? [Y/n]: " install
install=${install:-Y}

case $install in
  [yY])
      read -p "Do you want me to try to find your Lutris location? [Y/n]" doFind
      doFind=${doFind:-y}
      case $doFind in
        [yY])
          location=$(locate "lutris/runtime/dxvk" | grep -e "lutris/runtime/dxvk$" | head -n 1)
          read -p "Found location: ${location} - is this right? [y/n]" isCorrect
          isCorrect=${isCorrect:-y}
          case $isCorrect in
            [yY])
              location=$location
              ;;
            *)
              location="/bogus/location"
              ;;
          esac
          ;;
        *)
          location="/bogus/location"
          ;;
      esac

      while [[ ! -d $location ]] ; do
        read -p "Install location: [${location}]: " location
        location=${location:-~/.local/share/lutris/runtime/dxvk}
        if [[ ! -d $location ]]; then
          echo "Invalid install location: $location does not exist"
        fi
      done

      echo "Installing to ${location}"
      rm -rf $location/dxvk-master
      cp -R out/dxvk-master $location
      echo "dxvk-master installed. Enter 'dxvk-master' as your DXVK version in Lutris."
    ;;
  *)
    ;;
esac
